module.exports = [
  // ══════════════════════════════════════════════════════
  //  🛡️ DEFENSE ITEMS
  // ══════════════════════════════════════════════════════
  {
    id: "lock",
    name: "Steel Lock 🔐",
    price: 12_000,
    type: "defense",
    durability: 10,
    emoji: "🔐",
    description: "Reduces rob success chance by 25%.",
    effect: { robChanceReduction: 0.25 },
  },
  {
    id: "guard_dog",
    name: "Guard Dog 🐕",
    price: 40_000,
    type: "defense",
    durability: 15,
    emoji: "🐕",
    description: "Reduces rob success chance by 40%.",
    effect: { robChanceReduction: 0.40 },
  },
  {
    id: "alarm",
    name: "Security Alarm 🚨",
    price: 28_000,
    type: "defense",
    durability: 8,
    emoji: "🚨",
    description: "Increases robber cooldown by 30 min if triggered.",
    effect: { robCooldownIncrease: true },
  },
  {
    id: "insurance",
    name: "Insurance Policy 📜",
    price: 55_000,
    type: "defense",
    durability: 5,
    emoji: "📜",
    description: "Refunds 50% of stolen money back to you.",
    effect: { refundLoss: 0.5 },
  },
  {
    id: "vault",
    name: "Vault Upgrade 🏦",
    price: 95_000,
    type: "defense",
    durability: 20,
    emoji: "🏦",
    description: "Caps rob loss to 10% of wallet.",
    effect: { maxLossPercent: 0.10 },
  },

  // ══════════════════════════════════════════════════════
  //  🛠️ WORK TOOLS
  // ══════════════════════════════════════════════════════
  {
    id: "laptop",
    name: "Laptop 💻",
    price: 18_000,
    type: "tool",
    emoji: "💻",
    description: "Required for tech jobs. Boosts work earnings by 15%.",
    effect: { workBoost: 0.15, requiredForJob: ["programmer", "hacker"] },
  },
  {
    id: "pickaxe",
    name: "Pickaxe ⛏️",
    price: 8_000,
    type: "tool",
    emoji: "⛏️",
    description: "Required for mining jobs. Boosts earnings by 10%.",
    effect: { workBoost: 0.10, requiredForJob: ["miner"] },
  },
  {
    id: "fishing_rod",
    name: "Fishing Rod 🎣",
    price: 5_000,
    type: "tool",
    emoji: "🎣",
    description: "Required to use $fish. Higher tier = better catches.",
    effect: { fishingEnabled: true },
  },
  {
    id: "shovel",
    name: "Shovel 🪚",
    price: 4_500,
    type: "tool",
    emoji: "🪚",
    description: "Boosts $search earnings by 25%.",
    effect: { searchBoost: 0.25 },
  },
  {
    id: "stethoscope",
    name: "Stethoscope 🩺",
    price: 25_000,
    type: "tool",
    emoji: "🩺",
    description: "Required for doctor/nurse jobs. Boosts earnings by 20%.",
    effect: { workBoost: 0.20, requiredForJob: ["doctor", "nurse"] },
  },

  // ══════════════════════════════════════════════════════
  //  🌱 FARMING ITEMS
  // ══════════════════════════════════════════════════════
  {
    id: "watering_can",
    name: "Watering Can 🪣",
    price: 3_500,
    type: "farming",
    emoji: "🪣",
    description: "Reduces crop grow time by 10%. Gives 5 charges.",
    effect: { waterCharges: 5 },
  },
  {
    id: "fertilizer",
    name: "Fertilizer Bag 🌿",
    price: 7_000,
    type: "farming",
    emoji: "🌿",
    description: "Reduces crop grow time by 35%. One-time use.",
    effect: { fertilizeCharges: 1 },
  },
  {
    id: "premium_fertilizer",
    name: "Premium Fertilizer 💚",
    price: 20_000,
    type: "farming",
    emoji: "💚",
    description: "Reduces crop grow time by 60%. One-time use.",
    effect: { fertilizeCharges: 1, premiumFertilize: true },
  },

  // ══════════════════════════════════════════════════════
  //  🍔 CONSUMABLES
  // ══════════════════════════════════════════════════════
  {
    id: "pizza",
    name: "Pizza 🍕",
    price: 800,
    type: "consumable",
    emoji: "🍕",
    description: "Reduces work cooldown by 5 minutes.",
    effect: { reduceCooldown: { type: "work", amount: 5 * 60_000 } },
  },
  {
    id: "energy_drink",
    name: "Energy Drink ⚡",
    price: 1_500,
    type: "consumable",
    emoji: "⚡",
    description: "Reduces work cooldown by 12 minutes.",
    effect: { reduceCooldown: { type: "work", amount: 12 * 60_000 } },
  },
  {
    id: "coffee",
    name: "Coffee ☕",
    price: 600,
    type: "consumable",
    emoji: "☕",
    description: "Reduces work cooldown by 3 minutes.",
    effect: { reduceCooldown: { type: "work", amount: 3 * 60_000 } },
  },
  {
    id: "medkit",
    name: "Medkit 💊",
    price: 4_000,
    type: "consumable",
    emoji: "💊",
    description: "Restores 50 health points.",
    effect: { healAmount: 50 },
  },
  {
    id: "bandage",
    name: "Bandage 🩹",
    price: 1_200,
    type: "consumable",
    emoji: "🩹",
    description: "Restores 20 health points.",
    effect: { healAmount: 20 },
  },
  {
    id: "lucky_clover",
    name: "Lucky Clover 🍀",
    price: 12_000,
    type: "consumable",
    emoji: "🍀",
    description: "Boosts coin rewards by 25% for 1 hour.",
    effect: { coinBoost: 0.25, duration: 3_600_000 },
  },

  // ══════════════════════════════════════════════════════
  //  💎 PRESTIGE ITEMS
  // ══════════════════════════════════════════════════════
  {
    id: "prestige_coin_boost",
    name: "Coin Booster 🌟",
    price: 100_000,
    type: "prestige",
    emoji: "🌟",
    description: "Permanently increases all coin gains by +20%.",
    requiredPrestigeLevel: 1,
    perk: "coinBoost",
  },
  {
    id: "prestige_xp_boost",
    name: "XP Booster ⭐",
    price: 100_000,
    type: "prestige",
    emoji: "⭐",
    description: "Permanently increases all XP gains by +20%.",
    requiredPrestigeLevel: 1,
    perk: "xpBoost",
  },
  {
    id: "prestige_fast_work",
    name: "Fast Work Pass ⚡",
    price: 150_000,
    type: "prestige",
    emoji: "⚡",
    description: "Permanently reduces your work cooldown by 50%.",
    requiredPrestigeLevel: 2,
    perk: "fastWork",
  },
  {
    id: "prestige_rob_immunity",
    name: "Anti-Rob Shield 🛡️",
    price: 200_000,
    type: "prestige",
    emoji: "🛡️",
    description: "You cannot be robbed while this is active.",
    requiredPrestigeLevel: 3,
    perk: "robImmunity",
  },

  // ══════════════════════════════════════════════════════
  //  ✨ SPECIAL ITEMS
  // ══════════════════════════════════════════════════════
  {
    id: "ping_reaction",
    name: "Ping Reaction Role 🔔",
    price: 350_000,
    type: "special",
    emoji: "🔔",
    description: "Bot reacts with emojis when you are mentioned.",
    is_exclusive: true,
    duration: 999 * 365 * 24 * 60 * 60 * 1000,
  },
  {
    id: "custom_role",
    name: "Custom Role 🎭",
    price: 15_000_000,
    type: "special",
    emoji: "🎭",
    description: "Get a personal custom role for 2 months.",
    is_exclusive: true,
    duration: 60 * 24 * 60 * 60 * 1000,
  },
  {
    id: "clan_role",
    name: "Clan Role 🛡️",
    price: 20_000_000,
    type: "special",
    emoji: "🛡️",
    description: "Custom role for all clan members. Needs 50M clan bank. Lasts 2 months.",
    is_exclusive: true,
    duration: 60 * 24 * 60 * 60 * 1000,
  },
];
